#!/bin/bash

if [ "${MFA_PROVIDER}" == "duo" ]; then
  echo "- Enabling DUO MFA"
  echo "#%PAM-1.0" > /etc/pam.d/mfa
  echo "auth include duo" >> /etc/pam.d/mfa
  if [ -z "${DUO_IKEY}" ]; then
    echo "DUO_IKEY not defined"
    exit 1;
  fi

  if [ -z "${DUO_SKEY}" ]; then
    echo "DUO_SKEY not defined"
    exit 1;
  fi

  if [ -z "${DUO_HOST}" ]; then
    echo "DUO_HOST not defined"
    exit 1;
  fi

  if [[ "$DUO_AUTOPUSH" == "yes" && "$DUO_VERIFIED_PUSH" == "yes" ]]; then
      echo "DUO_AUTOPUSH and DUO_VERIFIED_PUSH are mutually exclusive, both cannot be enabled!"
      exit 1;
  fi

  if [ "$DUO_HTTPS_TIMEOUT" -lt 0 ]; then
    echo "WARNING: DUO_HTTPS_TIMEOUT cannot be negative, setting to 0"
    export DUO_HTTPS_TIMEOUT=0
  fi

  envsubst < /etc/pam_duo.conf.env > /etc/pam_duo.conf
  chmod 600 /etc/pam_duo.conf
fi
